# site settings
title: Tarantula Fiddle
subtitle: Francesca Caruso
email: francesca.amadee@gmail.com
description: The music homepage of Francesca Amadée Caruso
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://tarantulafiddle.com # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# for form submission
formspree_id: mkggdwbn

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://instagram.com/frankpianissimo
  LinkedIn: https://www.linkedin.com/in/francesca-a-caruso
  Twitter: 
  Facebook:
  Slack:
  envelope: mailto:francesca.amadee@gmail.com # email address

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
